*ADS-A Week 1 Assignment 1*

# Basic Python Exercises

These exercises touch only a very small subset of Python. The reason this subset has been chosen is that:
1. It contains basic Python idiom that deviates substantially from what you are used to in languages such as C# and Java.
2. We have to be familiar with the idiom in it as we will make extensive use of it in solving data science problems.

For help in solving the exercises you can consult this online [Python tutorial](https://docs.python.org/3.4/tutorial/).

## String Exercises

Besides numbers, Python can also manipulate strings, which can be expressed in several ways. They can be enclosed in single quotes ('...') or double quotes ("...") with the same result.

### String Indexing

In [1]:
# Get the substring 'Fontys' from 'Fontys Machine Learning'

# Solution without variables
'Fontys Machine Learning'[:6]

# Solution with variables
a = 'Fontys Machine Learning'
b = a[0:6]        # Characters from position 0 (included) to 6 (excluded)
print(b)

# Yet another solution
b = a[:6]  

Fontys


In [4]:
## Get the substring 'Machine' from 'Fontys Machine Learning'

# Your code ...
c = a[7:14]
print(c)

Machine


``str[start:end:stride]`` slices str from position start to position end taking steps of length stride. Note how the start is always included, and the end always excluded. This makes sure that ``s[:i] + s[i:]`` is always equal to ``s``. Negative strides go backwards through string. ``[:]`` (single colon) refers to all elements of a string. ``[1:]`` is equivalent to "1 to end".

One way to remember how slices work is to think of the indices as pointing between characters, with the left edge of the first character numbered 0. Then the right edge of the last character of a string of n characters has index n, for example:

<pre>
 +---+---+---+---+---+---+
 | P | y | t | h | o | n |
 +---+---+---+---+---+---+
 0   1   2   3   4   5   6
-6  -5  -4  -3  -2  -1
</pre>

In [5]:
# What is the result of this expression, explain!
'Fontys'[:] == 'Fontys'[0:len('Fontys'):1]

True

`'Fontys'[:]` returns the entire string `"Fontys"` because both the indexes are empty.

`len('Fontys')` will return the lenght of the string inside. This will be 6.

This means the code becomes `'Fontys'[0:6:1]`, 0 is the start index and 6 is the end index, we can just remove these as they don't make any difference. This results in the code `'Fontys'[::1]` we can again simplify this by removing the stepsize which is still the default (1).

The last simplified code is: `'Fontys'[:] == 'Fontys'[:]`, both sides return the same `'Fontys'` string and therefor the statement is true.

In [9]:
# Using slicing, create the string "Bye' from 'Bicycle' (you have to collect characters at positions 0, 3 and 6)

## Your code ...
o = 'Bicycle'
print(o[::3])

Bye


In [11]:
# Reverse the string 'Fontys'

## Your code ...
print('Fontys'[::-1])

sytnoF


In [231]:
# Decide if a string is a palindrome, create a function for this, time the execution time of this function
s = 'legermeetsysteemregel'

## Your code ...
def is_palindrome(s):
    reverse = s[::-1]
    
    return (s == reverse)

%timeit is_palindrome(s)

The slowest run took 16.68 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 461 ns per loop


In [30]:
# Improve your is_palindrome() function, it should return true only if a sentence (ignoring blanks, character case 
# and punctuation) is a palindrome, e.g is_palindrome('A man, a plan, a canal, Panama') should return True

## Your code ...
def is_palindrome(s):
    chars = {' ', ',', '.'} #more characters that need to be removed can be added here
    e = s
    for char in chars:
        e = e.replace(char, '')
    e = e.lower()
    reverse = e[::-1]
    return (e == reverse)

print(is_palindrome('A man, a plan, a canal, Panama'))

True


### Create Formatted String Output

In [37]:
# Create the string 'The %s at %s has %d students!' where the placeholders
# are substituted with 'ADS-A Specialisation', 'FHICT', and 56

# See: https://docs.python.org/3.4/library/string.html#format-string-syntax

## Your code ...
a = 'The %s at %s has %d students!'
print(a%('ADS-A Specialisation', 'FHICT', 56))

The ADS-A Specialisation at FHICT has 56 students!


The method ``split(str,num)`` returns a list of all the words in the string, using ``str`` as the separator (splits on all whitespace if left unspecified), optionally limiting the number of splits to ``num``.

In [40]:
# Split user name and domain in a mail address:

## Your code ...
e = 'b.debever@student.fontys.nl'
b = e.split('@')
name = b[0]
domain = b[1]
print('Name: ' + name)
print('Domain: ' + domain)

Name: b.debever
Domain: student.fontys.nl


In [42]:
# Using a format string specifier, create the string 'lgh(at)fontys.nl' from addr
# you could use the parameter unpacking operator *

## Your code ...
#Can't know contents of variable addr

## List Exercises

Python knows a number of compound data types, used to group together other values. The most versatile is the list, which can be written as a list of comma-separated values (items) between square brackets. Lists might contain items of different types, but usually the items all have the same type.

### List Creation

In [44]:
# Create a list of numbers 1,2,3
[1,2,3]

In [232]:
# Create a list of (1-character) strings from the string 'Fontys', try to do it using list comprehension
# list('Fontys') getting an error on this line for some reason

## Your code ...
newlist = [l for l in 'Fontys']
print(newlist)

['F', 'o', 'n', 't', 'y', 's']


In [164]:
# Create a list of the objects 1, [], 'Fontys', ['Fontys, 1]
# [] means empty list

## Your code ...
list1 = [[], 'Fontys', ['Fontys', 1]]
print(list1)

[[], 'Fontys', ['Fontys', 1]]


In [62]:
# Create a list for the integers between 0 and 20 ([0..20), or 0 <= n < 20)
# Use the range() function, which is actually a type (immutable sequence) that can be iterated over.

## Your code ...
print([i for i in range(0,21)])
    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [63]:
# Create the integer list [11..21]

## Your code ...
print([i for i in range(11, 22)])

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


In [67]:
# Create a list for all even integer numbers between 90 and 100.

## Your code ...
print([i for i in range(90,101) if i % 2 == 0])

[90, 92, 94, 96, 98, 100]


List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

For example, assume we want to create a list of squares, like:

<pre>
>>> squares = []
>>> for x in range(10):
...   squares.append(x**2)
...
>>> squares
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
</pre>

Note that this creates (or overwrites) a variable named x that still exists after the loop completes. We can calculate the list of squares without any side effects using:

<pre>
squares = [x**2 for x in range(10)]
</pre>

In [69]:
# Create a list of  all integers between 0 and 100 that can be divided by 3 and are uneven, try list comprehension

## Your code ...
print([i for i in range(0, 101) if i % 3 == 0 & i % 2 != 1])

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


### List Indexing and Slicing

In [ ]:
# First some examples. Always remember:
# - the list (sequence) is always traversed (processed) left to right
# - the first index specifies the first item you want in your slice
# - the second index specifies the first item you don’t want in your slice
# - the third slice index is the stride length with which you step through the list to pick the elements of your slice

print(1, [1,2,3,4][:])
print(2, [1,2,3,4][1:])
print(3, [1,2,3,4][:1])
print(4, [1,2,3,4][:-1])
print(5, [1,2,3,4][0:4])
print(6, [1,2,3,4][1::-1])
print(7, [1,2,3,4][1::-3])
print(8, [1,2,3,4][::])         # often used to make a complete (shallow) copy of the list
print(9, [1,2,3,4][::1])
print(10, [1,2,3,4][::-1])      # often used to make a reversed copy of the list
print(11, [1,2,3,4][0:4:-1])    # if stride is negative, start must be > end!!
print(12, [1,2,3,4][4:0:-1])    # start > end

In [70]:
# Get list [1,4] from list [1,2,3,4]

## Your code ...
print([1,2,3,4][::3])

[1, 4]


In [233]:
# Get first and last element of any list
l = [1,2,3]
l2 = [1,2,3,4,5,6,7]
## Your code ...

def first_and_last(l):
    return l[0:len(l): len(l)-1]
print(first_and_last(l))
print(first_and_last(l2))

[1, 3]
[1, 7]


### List and String

In [86]:
# Create the string 'ads' from list ['a', 'd', 's']

## Your code ...
#first try
s = ''
for char in ['a', 'd', 's']:
    s += char
print(s)

#After seeing .join
print(''.join(['a', 'd', 's']))

ads


In [81]:
# Why does str(['a', 'd', 's']) not work in previous exercise?

#Literally converts it into a string instead of the items in the list

In [240]:
# Create the string 'a d s' from string 'ads'

## Your code ...
c = 'ads'
r = ''
i = 1
for char in c:
    if i != len(c):
        r += char + ' '
    else:
        r += char
    i += 1
print(r)

a d s


In [85]:
# Create the string '123' from list [1,2,3]
# Try: "".join([1,2,3]); why does it not work?   
##"".join([1,2,3])
#These are seen as intergers instead of characters/strings
# Your code ...
"".join([str(i) for i in [1,2,3]])

'123'

In [89]:
# Create the list [1,2,3] from string '123'

## Your code ...
print([int(i) for i in '123'])

[1, 2, 3]


In [90]:
# Create the list ['a', 'd', 's'] from 'a d s' with split()

## Your code ...
print('a d s'.split(' '))

['a', 'd', 's']


## Tuple Exercises

We saw that lists and strings have many common properties, such as indexing and slicing operations. They are two examples of sequence data types. One of them is the tuple.

A tuple consists of a number of values separated by commas.

In [97]:
# Create the list of tuples [(1, 2), (3, 4)] from [1, 2, 3, 4]
l = [1, 2, 3, 4]

# the non-idiomatic way would be:
l1 = []
for i in range(0, len(l)-1, 2):
    l1.append((l[i], l[i+1]))
l1

# Test what happens if l is the empty list, has 1, 2 or any uneven number of elements
#Untill an even amount of elements is presented, it will not display it.

[(1, 2), (3, 4)]

In [3]:
# Create the list of tuples the idiomatic way, using list comprehension
# run your tests from previous exercise

## Your code ...
l = [1,2,3,4]
print([(l[i], l[i+1]) for i in range(0, len(l)) if (i % 2 == 0) & ((i+1) < len(l))])
#after some alterations it will now work properly.

[(1, 2), (3, 4)]


In [2]:
# Now, create the same list of tuples using zip(), again run your tests
## Your code ...
l = [1,2,3,4]
l1 = l[::2]
l2 = l[1:len(l):2]
l3 = list(zip(l1, l2))
print(l3)

[(1, 2), (3, 4)]


In [175]:
# Flatten the list of tuples [(1, 2), (3, 4)] to [1, 2, 3, 4]
lt = [(1, 2), (3, 4)]

## Your code with a loop
l = []
for item in lt:
    for item2 in item:
            l.append(item2)
print(l)

[1, 2, 3, 4]


In [252]:
## Your code with list comprehension
lt = [(1, 2), (3, 4)]
print([item3 for item in lt for item3 in item])

[1, 2, 3, 4]


In [190]:
# Explain (by consulting the ref manual) why this also works
lt = [(1, 2), (3, 4)]
list(sum(lt, ()))
#This adds the tuple value with an empty tuple, serperating the values into a new bigger tuple.
#The list just makes it one big list instead of a tuple

(1, 2, 3, 4)


In [183]:
# Now for an interesting strecht of mind: use only sum() to sum all numbers in lt
lt = [(1, 2), (3, 4)]

## Your code ...
print(sum(list(sum(lt, ()))))

10


## List as Matrix Exercises 

In [ ]:
# A matrix constructed from lists is a list of lists

In [253]:
# Add a P(ass), F(ail) mark to a list of numeric marks
# transform [6,4,7] into the matrix [[6,'P'], [4,'F'], [7,'P']]

marks = [6, 4, 7]

## Your code with a for loop ...
textmarks = []
result = ''
for mark in marks:
     if (mark > 5.5) : result = 'P'  
     else : result = 'F'
     textmarks.append([mark, result])
print(textmarks)

[[6, 'P'], [4, 'F'], [7, 'P']]


In [196]:
## Your code with list comprehension (more idiomatic)
marks = [6,4,7]
textmarks = [[mark, 'P'] if (mark > 5) else [mark, 'F'] for mark in marks ]
print(textmarks)

[[6, 'P'], [4, 'F'], [7, 'P']]


In [260]:
# ** Optionally **
# Transpose the 2 x 3 matrix [[1,2,3], [4,5,6]] to the 3 x 2 matrix [[1,4], [2,5], [3,6]]
# Generalize to transposing n x m matrix to m x n matrix; a straightforward list traversal solution
# would be nested for loops
mx = [[1,2,3], [4,5,6]]

## Your code ...

ls = []
for i in range(0,len(mx[0])):
      ls.append([mx[0][i], mx[1][i]])  
print(ls)

[[1, 4], [2, 5], [3, 6]]


In [267]:
# ** Optionally **
# We can morph this nested for loop solution into the more idiomatic (pythonic) nested list comprehension solution

## Your code ...
print(list([mx[0][i], mx[1][i]] for i in range(0, len(mx[0]))))

[[1, 4], [2, 5], [3, 6]]


In [314]:
# ** Optionally **
# The seasoned python pro will probably use zip and the unary unpack (*) operator (https://goo.gl/bHWS2S)
# on top of that: the zip() solution is faster

## Your code ...
ls = [[value1, value2] for value1, value2 in list((zip(mx[0], mx[1])))]
print(ls)

[[1, 4], [2, 5], [3, 6]]


In [205]:
# Sneak preview for next week, the easy way with numpy!!
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
a.transpose()      # a.T also works!

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [209]:
# Create the matrix [[1,0],[2,0],[3,2]] by merging the lists [1,2,3] and ['O', 'O', 'G'], where each character is 
# mapped to its position in the lookup list ['O', 'V', 'G']
# Tip: use the index() method to determine the position of a value in a sequence

## Your code ...
import numpy as np
l2 = ['O', 'O', 'G']
ll = ['O', 'V', 'G']
a = np.array([l1, [ll.index(char) for char in l2]])
print(a)
a.transpose()

[[1 2 3]
 [0 0 2]]


array([[1, 0],
       [2, 0],
       [3, 2]])

## Dictionary Exercises

In [ ]:
# You all know dictionaries (associative arrays) from C#, Java, PHP; here is how you define them in Python
d = {'k1': [1], 'k2': [2], 'k3': [3]}
d['k2'] = 3
d['k4'] = [4]
d

In [283]:
# Or:
keys = ['k1','k2','k3']
values = [[1],[2],[3]]
dict(zip(keys, values))    # zip() returns iterable of tuples that can be converted into dictionary

{'k1': [1], 'k2': [2], 'k3': [3]}

In [211]:
# Or, using dict comprehension
# You might be tempted to do {k: v for k in keys for v in values}
# Why doesn't this work?
# Create the correct version

## Your code ...
keys = ['k1','k2','k3']
values = [[1],[2],[3]]
zipped = zip(keys, values)
d = {key: value for (key, value) in zipped}
print(d)

{'k1': [1], 'k2': [2], 'k3': [3]}


In [229]:
# Create a Python function that returns a word count dictionary for a piece of text
# e.g. count_words("This and this and this also") == {'this': 3, 'and': 2, 'also': 1}

## Your code ...

def count_words(s):
    d = dict()
    s = s.lower()
    e = s.split(' ')
    for word in e:
        d[word] = d.get(word, 0) + 1
    return d
count_words("This and this and this also") == {'this': 3, 'and': 2, 'also': 1}

True